<?php

namespace Shop\MenuBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DataMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataMenuRepository extends EntityRepository {

    

}
