<?php

namespace Shop\MenuBundle\Repository;

/**
 * GhcodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GhcodeRepository extends \Doctrine\ORM\EntityRepository
{
}
