<?php

namespace Shop\MenuBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemsRepository extends EntityRepository {

    public function findBySerchCodeOrderedById($serch) {

        $dql = $this->getEntityManager()
            ->getRepository('ShopMenuBundle:Ghcode')
            ->createQueryBuilder('i');

        $dql = $dql->where('i.code = :serch')
            ->setParameter('serch', $serch)
            ->getQuery();
        $items = $dql->getResult();
        $array_gh = array();
        foreach ($items as $item) {
            $array_gh[] = $item->getItemId();
        }
        $array_gh = array_unique($array_gh);
        //var_dump($array_gh);

/*        if (count($array_gh) != 0){

            $query = $this->createQueryBuilder('i')
                ->andWhere('i.itemId IN (:ids)')
                ->setParameter('ids', $array_gh, \Doctrine\DBAL\Connection::PARAM_STR_ARRAY)
                ->groupby('i.itemId');

            $query = $query->orderBy('i.id', 'ASC')
                ->getQuery();

        }else{*/

            //echo $serch;
            $query = $this->createQueryBuilder('i')
                ->andwhere('i.itemId LIKE :serch')
                ->orWhere('i.acsesorisId LIKE :serch');

            if (count($array_gh) != 0){
                $query = $query->orWhere('i.itemId IN (:ids)')
                                ->setParameter('ids', $array_gh, \Doctrine\DBAL\Connection::PARAM_STR_ARRAY);
            }

            $query = $query->setParameter('serch', '%'.$serch.'%')
                ->groupby('i.itemId');

            $query = $query->orderBy('i.id', 'ASC')
                ->getQuery();
        //}


       // echo $query->getSQL();
        
        return $query;
        
    }    
    
    public function findByIdOrderedById($model_id, $auto_id, $data_id, $side, $t, $t1, $t2, $t3) {

        $tId = "";
        if($t){

            $arr = array();
            if ($t2){
                $arr[] = 2;
            }
            if ($t1){
                $arr[] = 3;
            }
            if ($t3){
                $arr[] = 5;
            }

            $tId = " and i.tId IN(".implode(",",$arr).")";

        }

        $sideId = $side ? " and i.sideId = :side" : ""; 
                
        $query = $this->createQueryBuilder('i')
            ->andwhere('i.modelMenuId = :model_id and i.autoMenuId = :auto_id and i.dataMenuId = :data_id'.$sideId.$tId)
            ->setParameter('model_id', $model_id)
            ->setParameter('auto_id', $auto_id)
            ->setParameter('data_id', $data_id);
        
        if ($side) {
            $query = $query->setParameter('side', $side);                
        }

        $query = $query->orderBy('i.id', 'ASC')
                 ->getQuery();
        return $query;
        
    }
    
}
