admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin_user:
    resource: "@AdminBundle/Resources/config/routing/user.yml"
    prefix:   /user
    
admin_modelmenu:
     resource: "@AdminBundle/Resources/config/routing/modelmenu.yml"
     prefix:   /modelmenu