admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin_user:
    resource: "@AdminBundle/Resources/config/routing/user.yml"
    prefix:   /user
    
admin_modelmenu:
     resource: "@AdminBundle/Resources/config/routing/modelmenu.yml"
     prefix:   /modelmenu
          
admin_automenu:
    resource: "@AdminBundle/Resources/config/routing/automenu.yml"
    prefix:   /automenu

admin_datamenu:
    resource: "@AdminBundle/Resources/config/routing/datamenu.yml"
    prefix:   /datamenu

admin_items:
    resource: "@AdminBundle/Resources/config/routing/items.yml"
    prefix:   /items
    
admin_about:
    resource: "@AdminBundle/Resources/config/routing/about.yml"
    prefix:   /about
