<?php

namespace AdminBundle\Repository;

/**
 * AboutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PercentRepository extends \Doctrine\ORM\EntityRepository
{
}
