shop_menu_modelmenu:
     resource: "@ShopMenuBundle/Resources/config/routing/modelmenu.yml"
     prefix:   /modelmenu

shop_menu_test:
    resource: "@ShopMenuBundle/Resources/config/routing/test.yml"
    prefix:   /test

shop_menu_homepage:
    path:     /
    defaults: { _controller: ShopMenuBundle:Default:index }

shop_menu_test:
    path:     /test
    defaults: { _controller: ShopMenuBundle:Default:test }
    
