
shop_menu_homepage:
    path:     /
    defaults: { _controller: ShopMenuBundle:Default:index }

shop_сontact:
    path:     /сontact
    defaults: { _controller: ShopMenuBundle:Default:сontact }

shop_about:
    path:     /about
    defaults: { _controller: ShopMenuBundle:Default:about }
    
products:
    resource: "@ShopMenuBundle/Resources/config/routing/products.yml"
    prefix:   /products

shop_mobil:
    path:     /mobil
    defaults: { _controller: ShopMenuBundle:Default:mobile }