security_user_user:
    resource: "@SecurityUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

security_user_homepage:
    path:     /
    defaults: { _controller: SecurityUserBundle:Default:index }

security_user_login:
    path:     /login
    defaults: { _controller: SecurityUserBundle:Login:login }

security_user_login_check:
    path:     /login_check
    defaults: { _controller: SecurityUserBundle:Login:login_check }

security_user_logout:
    path:     /logout
    defaults: { _controller: SecurityUserBundle:Login:logout }