security_user_user:
    resource: "@SecurityUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

security_user_homepage:
    path:     /
    defaults: { _controller: SecurityUserBundle:Default:index }
